displayName=No Trolls In Raids
author=BloatPlug
description=Automatically turns names red when a player from your ignore list appears in your ToB or ToA party.
tags=tob,toa,raid,ignore
version=1.0.0
plugins=com.NoTrollsInParty.NoTrollsInRaidsPlugin
build=standard